# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 64mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: "pi"
      POSTGRES_USER: "pi"
      POSTGRES_PASSWORD: 5620925
    
    ports:
      - "5432:5432"

  pgadmin4:
    image: adminer
    restart: always
    ports:
      - 8080:8080
